# Generated by Django 4.2.5 on 2023-09-19 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='Favourite'),
        ),
    ]
